import { Campaign, CampaignItem, CsvStatus, Status } from "~/index";
import { contCampaignId } from "./utils";
import { client } from "./client";
import * as fs from "fs";
import * as path from "path";
import { CampaignImport } from "~/models/CampaignImport";
import { sleep } from "~/utils";
import { PaginatedResponseV3 } from "~/models/Response.v3";

let file: Uint8Array = null as unknown as Uint8Array;
let campaign: Campaign = null as unknown as Campaign;
let imprt: CampaignImport = null as unknown as CampaignImport;

beforeAll(async function () {
  campaign = await client.getCampaign(contCampaignId);

  file = fs.readFileSync(path.join(__dirname, "assets/test.csv"));
});

beforeEach(async function () {
  imprt = await campaign.createImport({
    mapping: {
      recipient: {
        city: "{{City}}",
        name: "{{FirstName}} {{LastName}}",
        address: "{{Street}} {{HouseNr}}",
        country: "{{Country}}",
        postalCode: "{{ZIP}}",
      },
      mergeVariables: {
        name: "{{FirstName}}",
        coupon: "{{Coupon}}",
      },
    },
    file: file,
    draft: true,
  });
});

afterAll(async function () {
  await imprt.cancel();
});

describe("refresh", function () {
  it("should refresh the csv order", async function () {
    // precondition
    if (imprt.status !== CsvStatus.import_created) {
      return;
    }

    // arrange

    // act
    while (imprt.status === CsvStatus.import_created) {
      await imprt.refresh();
      await sleep(1000);
    }

    // assert
    expect(imprt.status).not.toEqual(CsvStatus.import_created);
  }, 30000);
});

describe("getItems", function () {
  it("should get items generated by the csv", async function () {
    // arrange
    await imprt.process();

    // act
    while (imprt.counts.processed < 1) {
      await imprt.refresh();
      await sleep(1000);
    }

    await imprt.refresh();

    const items = await imprt.getItems({
      page: 1,
      limit: 200,
      filter: { draft: true },
    });

    // assert
    expect(items).toBeInstanceOf(PaginatedResponseV3);
    expect(items.data.length).toBe(imprt.counts.total);
    expect(
      items.data.filter((x) => x.status === Status.order_failed).length,
    ).toBe(imprt.counts.failed);
    expect(
      items.data.filter((x) => x.status !== Status.order_failed).length,
    ).toBe(imprt.counts.processed);
  }, 30_000);
});

describe("cancel", function () {
  it("should cancel the import", async function () {
    // arrange

    // act
    await imprt.cancel();

    // assert
    expect(imprt.status).toEqual(CsvStatus.import_cancelled);
  });
});

describe("process", function () {
  it("should process the import", async function () {
    // arrange

    // act
    await imprt.process();

    while (
      imprt.status !== CsvStatus.import_processed ||
      imprt.counts.processed < imprt.counts.estimated
    ) {
      await imprt.refresh();
      await sleep(1000);
    }

    // assert
    expect(imprt.status).toEqual(CsvStatus.import_processed);
    expect(imprt.counts.processed).toBe(2);
    expect(imprt.counts.total).toBe(2);
  }, 30000);
});

describe("previewRow", function () {
  it("should preview the row", async function () {
    // arrange
    await imprt.process();

    // act
    const item = await imprt.previewRow(1);

    // assert
    expect(item).toBeDefined();
    expect(item).toBeInstanceOf(CampaignItem);
    expect(item.recipient.name).toBe("John Doe");
  }, 30000);
});

describe("send", function () {
  it("should mark all items as non-draft", async function () {
    // arrange
    await imprt.send();

    // act
    while (imprt.counts.processed < imprt.counts.estimated) {
      await imprt.refresh();
      await sleep(1000);
    }

    const items = await imprt.getItems({
      filter: {
        draft: false,
      },
    });

    // assert
    expect(items.data.length).toBe(imprt.counts.processed);
  }, 30000);
});

describe("createUnsafe", function () {
  it("should return an interactable instance", function () {
    // act
    const imprt = CampaignImport.createUnsafe(client, {
      campaignId: contCampaignId,
      id: "some-id",
    });

    // assert
    expect(imprt).toBeInstanceOf(CampaignImport);
  });
});
