export const Format: {
  POSTCARD_A5: "POSTCARD_A5";
  POSTCARD_A6: "POSTCARD_A6";
  POSTCARD_SQ15: "POSTCARD_SQ15";
  GREETINGCARD_SQ14: "GREETINGCARD_SQ14";
} = {
  POSTCARD_A5: "POSTCARD_A5",
  POSTCARD_A6: "POSTCARD_A6",
  POSTCARD_SQ15: "POSTCARD_SQ15",
  GREETINGCARD_SQ14: "GREETINGCARD_SQ14",
};

export type Format = (typeof Format)[keyof typeof Format];
