export const Format: {
  POSTCARD_A5: "POSTCARD_A5";
  POSTCARD_A6: "POSTCARD_A6";
  POSTCARD_SQ14: "POSTCARD_SQ14";
  GREETINGCARD_SQ15: "GREETINGCARD_SQ15";
} = {
  POSTCARD_A5: "POSTCARD_A5",
  POSTCARD_A6: "POSTCARD_A6",
  POSTCARD_SQ14: "POSTCARD_SQ14",
  GREETINGCARD_SQ15: "GREETINGCARD_SQ15",
};

export type Format = (typeof Format)[keyof typeof Format];
