export enum MailingStatus {
  MAILING_CREATED = "MAILING_CREATED",
  MAILING_PAID = "MAILING_PAID",
  MAILING_PDF_CREATED = "MAILING_PDF_CREATED",
  MAILING_TRANSFERRED = "MAILING_TRANSFERRED",
  MAILING_PRINTED = "MAILING_PRINTED",
  MAILING_SENT = "MAILING_SENT",
}
