export enum MailingStatus {
  MAILING_CREATED = "MAILING_CREATED",
  MAILING_PAID = "MAILING_PAID",
  MAILING_PROCESSED = "MAILING_PROCESSED",
  MAILING_PDF_CREATED = "MAILING_PDF_CREATED",
  MAILING_TRANSFERRED = "MAILING_TRANSFERRED",
  MAILING_SENT = "MAILING_SENT",
}
