name: Update documentation
on:
  push:
    branches:
      - main
    paths:
      - docs/**

concurrency:
  group: wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    name: Update documentation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: spenserblack/actions-wiki@v0.3.0
        with:
          path: docs
